name: MeshMap Screenshot Service
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  workflow_call:
    inputs:
      fileName:
        description: Relative file path from the root directory
        required: true
        type: string
    outputs:
      resource_url:
        description: The URL of the generated resource.
        value: ${{ jobs.MeshMapScreenshot.outputs.resource_url }}
permissions:
  actions: read
  contents: write
  security-events: write
  statuses: write
  pull-requests: write
  id-token: write
jobs:
  MeshMapScreenshot:
    runs-on: ubuntu-latest
    outputs:
      resource_url: ${{ steps.test_result.outputs.resource_url }}
    steps:
      - name: Set PR number
        run: |
          export pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PULL_NO=$pull_number" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: layer5labs/meshmap-snapshot@v1
        with:
          path: action
      - id: test_result
        uses: layer5labs/meshmap-snapshot@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mesheryToken: ${{ secrets.MESHERY_TOKEN }}
          prNumber: ${{ env.PULL_NO }}
          application_type: Kubernetes Manifest
          filePath: ${{ inputs.fileName == '' && '.github/workflows/maven.yml' || inputs.fileName }}
